name:                sm-dedupe
version:             0.1.0.0
github:              "DanJBarry/sm-dedupe"
license:             MIT
author:              "Daniel Barry"
maintainer:          "dbarry@stevens.edu"
copyright:           "2020 Daniel Barry"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sm-dedupe#readme>

dependencies:
- base >= 4.13.0 && < 4.14
- directory >= 1.3.6.0 && < 1.4
- filepath >= 1.4.2.1 && < 1.5
- SHA >= 1.6.4.4 && < 1.7
- bytestring >= 0.10.10.0 && < 0.11
- parsec >= 3.1.14.0 && < 3.2
- text >= 1.2.4.0 && < 1.3
- containers >= 0.6.2.1 && < 0.7
- cmdargs >= 0.10.20 && < 0.11
- path == 0.7.0 || (> 0.7.1 && < 0.8)
- path-io >= 1.6.0 && < 1.7

library:
  source-dirs: src

executables:
  sm-dedupe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O3
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sm-dedupe

tests:
  sm-dedupe-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sm-dedupe
