name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu, macos]

    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.8.3'
        stack-version: 'latest'

    - name: Build
      run: stack build --system-ghc
    - name: Copy over binary
      run: |
          mkdir -p ./dist/bin
          mv "$(stack path --local-install-root --system-ghc)/bin" ./dist
    - uses: actions/upload-artifact@v2
      with:
        name: sm-dedupe-${{ runner.os }}
        path: ./dist/bin/sm-dedupe
  build_windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.8.3'
        stack-version: 'latest'

    - name: Build
      run: stack build --system-ghc
    - name: Copy over binary
      shell: powershell
      run: |
          mkdir -p .\dist
          move "$(stack path --local-install-root --system-ghc)\bin" .\dist
    - uses: actions/upload-artifact@v2
      with:
        name: sm-dedupe-${{ runner.os }}
        path: .\dist\bin\sm-dedupe.exe
